export type StageId = 'pre1' | 'grade1' | 'grade2' | 'grade3' | 'grade4' | 'grade5';
export type Domain = 'rhythm' | 'notation' | 'keys' | 'intervals' | 'harmony' | 'terms';
export type SkillId = 'pulse'|'crotchet'|'minim'|'semibreve'|'rests'|'quavers'|'compare-values'|'bars'|'simple-time'|'dots-ties'|'semiquavers'|'rhythm-writing'|'stave'|'treble-notes'|'bass-notes'|'accidentals'|'tones-semitones'|'major-scales'|'key-signatures'|'scale-degrees'|'interval-number'|'tonic-triad'|'dynamics'|'articulation'|'tempo-terms';
export type Lesson = { id:string; stage:'pre1'|'grade1'; order:number; title:string; minutes:number; domain:Domain; skills:SkillId[]; explanation:string; rule:string; example:string };
export type GradeMap = { id:StageId; title:string; level:string; domains:{domain:Domain;outcomes:string[]}[] };

export const lessons: Lesson[] = [
  { id:'p1-beat', stage:'pre1', order:1, title:'The beat', minutes:15, domain:'rhythm', skills:['pulse'], explanation:'A beat is the steady counting framework underneath written music. Beats continue evenly whether a note sounds or a rest is shown.', rule:'Equal beat boxes represent equal lengths of time.', example:'Count 1–2–3–4 evenly. Each number marks one beat.' },
  { id:'p1-crotchet', stage:'pre1', order:2, title:'One sound for one beat', minutes:15, domain:'rhythm', skills:['pulse','crotchet'], explanation:'A crotchet fills one beat in the simple time used at this level.', rule:'One crotchet = one beat.', example:'Four crotchets fill four beats: 1 + 1 + 1 + 1.' },
  { id:'p1-minim', stage:'pre1', order:3, title:'Notes that last longer', minutes:15, domain:'rhythm', skills:['crotchet','minim','compare-values'], explanation:'A minim lasts across two crotchet beats. Its sound begins on the first beat and continues through the second.', rule:'One minim = two crotchets = two beats.', example:'Two minims fill the same time as four crotchets.' },
  { id:'p1-semibreve', stage:'pre1', order:4, title:'The four-beat note', minutes:15, domain:'rhythm', skills:['semibreve','compare-values'], explanation:'A semibreve lasts for four crotchet beats in simple time.', rule:'One semibreve = two minims = four crotchets.', example:'A whole four-beat bar can contain one semibreve.' },
  { id:'p1-rests', stage:'pre1', order:5, title:'Silence still has length', minutes:15, domain:'rhythm', skills:['rests','compare-values'], explanation:'A rest tells us to remain silent for a measured length of time. The beat does not stop during a rest.', rule:'Every note value has a rest of the same duration.', example:'A crotchet rest is one silent beat; a minim rest is two silent beats.' },
  { id:'p1-quavers', stage:'pre1', order:6, title:'Two sounds inside one beat', minutes:15, domain:'rhythm', skills:['quavers','pulse'], explanation:'Two quavers divide one crotchet beat into two equal halves.', rule:'Two quavers = one crotchet beat.', example:'Count “1 and 2 and” to place two equal sounds in each beat.' },
  { id:'p1-bars', stage:'pre1', order:7, title:'Putting beats into bars', minutes:15, domain:'rhythm', skills:['bars','simple-time'], explanation:'Bar lines divide music into equal groups of beats. The top number of a simple time signature tells us how many beats belong in each bar.', rule:'Every complete bar must contain the number of beats promised by its time signature.', example:'In 4/4, each complete bar totals four crotchet beats.' },
  { id:'p1-stave', stage:'pre1', order:8, title:'The musical stave', minutes:15, domain:'notation', skills:['stave'], explanation:'Pitch is written on five lines and four spaces. Higher positions represent higher written pitches.', rule:'Count every line and space in sequence; never skip a position.', example:'A note moving from a line to the space above moves one step higher.' },
  { id:'p1-treble', stage:'pre1', order:9, title:'Treble-clef note names', minutes:15, domain:'notation', skills:['stave','treble-notes'], explanation:'The treble clef fixes the names of notes on the stave. Letter names continue A–B–C–D–E–F–G and repeat.', rule:'Moving to the next line or space moves to the next letter name.', example:'The treble-clef lines are E, G, B, D, F from bottom to top.' },
  { id:'p1-bass', stage:'pre1', order:10, title:'Bass-clef note names', minutes:15, domain:'notation', skills:['stave','bass-notes'], explanation:'The bass clef gives the stave a different pitch range and therefore different note names.', rule:'The letter sequence stays the same; the clef changes where it begins.', example:'The bass-clef lines are G, B, D, F, A from bottom to top.' },
  { id:'p1-signs', stage:'pre1', order:11, title:'Signs that change music', minutes:15, domain:'notation', skills:['accidentals','dynamics','articulation'], explanation:'Written signs can change pitch, loudness and the way notes are connected or separated.', rule:'Read each sign before deciding how the written music behaves.', example:'A sharp raises a note; forte means loud; staccato means short and detached.' },
  { id:'p1-review', stage:'pre1', order:12, title:'Foundation review', minutes:20, domain:'rhythm', skills:['pulse','crotchet','minim','semibreve','rests','quavers','bars','stave','treble-notes','bass-notes'], explanation:'This mixed review checks each foundation separately. It does not average weaknesses away.', rule:'A skill is secure only after correct answers on more than one occasion.', example:'The app selects the least-secure due skill after every answer.' },
  { id:'g1-values', stage:'grade1', order:1, title:'Complete note and rest values', minutes:20, domain:'rhythm', skills:['crotchet','minim','semibreve','quavers','semiquavers','rests','compare-values'], explanation:'Read, compare and combine semibreves, minims, crotchets, quavers and semiquavers with their equivalent rests.', rule:'Convert every value to a common beat fraction before combining it.', example:'Four semiquavers, two quavers and one crotchet each occupy one crotchet beat.' },
  { id:'g1-dots', stage:'grade1', order:2, title:'Dots and ties', minutes:20, domain:'rhythm', skills:['dots-ties','compare-values'], explanation:'A dot adds half of a note’s original value. A tie joins the duration of two notes of the same pitch.', rule:'Dotted value = original value + half the original value.', example:'A dotted minim lasts three crotchet beats.' },
  { id:'g1-time', stage:'grade1', order:3, title:'Simple time signatures', minutes:20, domain:'rhythm', skills:['simple-time','bars'], explanation:'Read and complete bars in 2/4, 3/4 and 4/4, including the common-time sign.', rule:'The top number counts beats; the lower number identifies the written beat unit.', example:'3/4 contains three crotchet beats per complete bar.' },
  { id:'g1-group', stage:'grade1', order:4, title:'Grouping and bar lines', minutes:20, domain:'rhythm', skills:['bars','rhythm-writing','semiquavers'], explanation:'Place bar lines and choose grouping that makes the beat structure immediately visible.', rule:'Notation should show where each beat begins and ends.', example:'Quavers within one crotchet beat are normally beamed together.' },
  { id:'g1-pitch', stage:'grade1', order:5, title:'Treble and bass pitch', minutes:20, domain:'notation', skills:['treble-notes','bass-notes','stave'], explanation:'Read and place notes in both clefs, including the small working range around each stave.', rule:'Use the clef, then count lines and spaces through the repeating musical alphabet.', example:'Middle C sits between the treble and bass staves on its own ledger line.' },
  { id:'g1-accidentals', stage:'grade1', order:6, title:'Accidentals, tones and semitones', minutes:20, domain:'notation', skills:['accidentals','tones-semitones'], explanation:'Apply sharps, flats and naturals and measure movement in tones and semitones.', rule:'An accidental applies to that pitch for the remainder of the bar unless cancelled or replaced.', example:'B to C and E to F are naturally occurring semitones.' },
  { id:'g1-scales', stage:'grade1', order:7, title:'C, G, D and F major', minutes:20, domain:'keys', skills:['major-scales','key-signatures'], explanation:'Construct and recognise the four foundational major scales and their key signatures.', rule:'A major scale follows tone–tone–semitone–tone–tone–tone–semitone.', example:'G major uses F sharp; F major uses B flat.' },
  { id:'g1-degrees', stage:'grade1', order:8, title:'Scale degrees and intervals', minutes:20, domain:'intervals', skills:['scale-degrees','interval-number'], explanation:'Number scale positions and measure written intervals by counting both the starting and finishing notes.', rule:'Interval numbers include both notes.', example:'C up to G counts C–D–E–F–G: a fifth.' },
  { id:'g1-triads', stage:'grade1', order:9, title:'The tonic triad', minutes:20, domain:'harmony', skills:['tonic-triad','major-scales'], explanation:'Build the tonic triad from the first, third and fifth degrees of a major scale.', rule:'A root-position tonic triad uses scale degrees 1–3–5.', example:'The tonic triad of G major is G–B–D.' },
  { id:'g1-language', stage:'grade1', order:10, title:'Musical terms and signs', minutes:20, domain:'terms', skills:['dynamics','articulation','tempo-terms'], explanation:'Recognise the foundational Italian terms, dynamic marks and articulation signs in written music.', rule:'Learn meaning and category, not just isolated translations.', example:'Allegro describes tempo; crescendo changes dynamics; legato changes articulation.' },
  { id:'g1-mixed', stage:'grade1', order:11, title:'Grade 1 mixed review', minutes:20, domain:'rhythm', skills:['rhythm-writing','simple-time','treble-notes','bass-notes','key-signatures','interval-number','tonic-triad','tempo-terms'], explanation:'Mixed generated questions test whether each topic can be recalled without being cued by a lesson heading.', rule:'Weak skills return sooner; secure skills are spaced further apart.', example:'A strong overall score cannot hide a weak individual skill.' },
];

export const gradeMap: GradeMap[] = [
  { id:'pre1', title:'Pre‑Grade 1', level:'First principles', domains:[{domain:'rhythm',outcomes:['Beat and equal duration','Crotchets, minims and semibreves','Equivalent rests','Quaver subdivision','Bars and simple metre']},{domain:'notation',outcomes:['Five-line stave','Treble and bass foundations','Basic signs']}]},
  { id:'grade1', title:'Grade 1', level:'Beginner', domains:[{domain:'rhythm',outcomes:['Full foundational values and rests','Dots and ties','2/4, 3/4 and 4/4','Correct grouping and bar lines']},{domain:'notation',outcomes:['Treble and bass fluency','Accidentals','Tones and semitones']},{domain:'keys',outcomes:['C, G, D and F major','Key signatures and scale degrees']},{domain:'intervals',outcomes:['Numbered intervals','Tonic triads']},{domain:'terms',outcomes:['Tempo, dynamics and articulation']}]},
  { id:'grade2', title:'Grade 2', level:'Developing beginner', domains:[{domain:'rhythm',outcomes:['Additional simple metres','Extended beaming and grouping','Triplet foundations']},{domain:'notation',outcomes:['Extended ledger lines','Enharmonic equivalents']},{domain:'keys',outcomes:['Further major and minor keys']},{domain:'intervals',outcomes:['Expanded interval and triad work']}]},
  { id:'grade3', title:'Grade 3', level:'Early intermediate', domains:[{domain:'rhythm',outcomes:['Compound time','Dotted-beat subdivision','Advanced grouping']},{domain:'keys',outcomes:['Expanded major and minor fluency']},{domain:'harmony',outcomes:['Primary chords and basic cadences']},{domain:'notation',outcomes:['Transposition and score reading']}]},
  { id:'grade4', title:'Grade 4', level:'Intermediate', domains:[{domain:'rhythm',outcomes:['9/8 and 12/8','Duplets','Complex rest grouping']},{domain:'notation',outcomes:['Alto clef','Advanced transposition']},{domain:'harmony',outcomes:['Chord function and cadence work']}]},
  { id:'grade5', title:'Grade 5', level:'Confident intermediate', domains:[{domain:'rhythm',outcomes:['Full simple and compound metre','Irregular grouping','Time conversion and rewriting']},{domain:'notation',outcomes:['Treble, bass, alto and tenor clefs']},{domain:'keys',outcomes:['Major and minor key fluency']},{domain:'harmony',outcomes:['Intervals, chords, inversions and cadences']},{domain:'terms',outcomes:['Complete intermediate score vocabulary']}]},
];

export const skillNames: Record<SkillId,string> = { pulse:'Steady beat',crotchet:'Crotchets',minim:'Minims',semibreve:'Semibreves',rests:'Rests',quavers:'Quavers','compare-values':'Comparing note values',bars:'Bars and bar lines','simple-time':'Simple time signatures','dots-ties':'Dots and ties',semiquavers:'Semiquavers','rhythm-writing':'Rhythmic grouping',stave:'The stave','treble-notes':'Treble-clef notes','bass-notes':'Bass-clef notes',accidentals:'Accidentals','tones-semitones':'Tones and semitones','major-scales':'Major scales','key-signatures':'Key signatures','scale-degrees':'Scale degrees','interval-number':'Numbered intervals','tonic-triad':'Tonic triads',dynamics:'Dynamics',articulation:'Articulation','tempo-terms':'Tempo terms' };
